project:
  type: website

lang: nb

filters:
  - pyodide-interaktiv
  - jsxgraph
  - math-exercise
  - py-exercise

website:
  title: "Matematikk 3A"
  sidebar:
    style: "docked"
    contents:
      - text: "IDE / Readme"
        file: pages/page1.qmd

      - text: "Emneinnhold"
        file: pages/emneinnhold.qmd

      - section: "Matematikk 1A"
        contents:
          - text: "Data - fagverk"
            file: projects-migrated/prosjekter-m1-jupyter/data1/index.qmd
          - text: "Mekanikk - fagverk"
            file: projects-migrated/prosjekter-m1-jupyter/mekanikk1/index.qmd
          - text: "Geomatikk - gps"
            file: projects-migrated/prosjekter-m1-jupyter/gps/index.qmd
          - text: "Kjemi - støkoiometri"
            file: projects-migrated/prosjekter-m1-jupyter/kjemi/index.qmd
          - text: "Elektriske kretser - likevekt"
            file: projects-migrated/prosjekter-m1-jupyter/kretser/index.qmd
          - text: "Logistikk - likevekt"
            file: projects-migrated/prosjekter-m1-jupyter/logistikk/index.qmd


      - section: "Matematikk 1B"
        contents:
          - text: "Data - markovkjede"
            file: projects-migrated/prosjekter-m1-jupyter/data-oving2-oppgave/index.qmd
          - text: "Mekanikk - knekking"
            file: projects-migrated/prosjekter-m1-jupyter/mekanikk2-ny/index.qmd
          - text: "Geomatikk - satelitt"
            file: projects-migrated/prosjekter-m1-jupyter/geomatikk2/index.qmd
          - text: "Kjemi - reaksjoner 1"
            file: projects-migrated/prosjekter-m1-jupyter/kjemi2/index.qmd
          - text: "Elektriske kretser - RLC 1"
            file: projects-migrated/prosjekter-m1-jupyter/kretser2/index.qmd
          - text: "Logistikk - dynamikk"
            file: projects-migrated/prosjekter-m1-jupyter/logistikk2/index.qmd
 

      - section: "Matematikk 1C"
        contents:
          - text: "Data - fagverk"
            file: projects-migrated/prosjekter-m1-jupyter/data-oving3-oppgave/index.qmd
          - text: "Mekanikk - spenning"
            file: projects-migrated/prosjekter-m1-jupyter/mekanikk3/index.qmd
          - text: "Geomatikk - wobble"
            file: projects-migrated/prosjekter-m1-jupyter/geomatikk3/index.qmd
          - text: "Kjemi - reaksjoner 2"
            file: projects-migrated/prosjekter-m1-jupyter/kjemi/index.qmd
          - text: "Elektriske kretser - RLC 2"
            file: projects-migrated/prosjekter-m1-jupyter/kretser3/index.qmd
          - text: "Logistikk - dynamikk 2"
            file: projects-migrated/prosjekter-m1-jupyter/logistikk3/index.qmd
    

      - section: "Matematikk 2 - PDE"
        contents:
 #         - text: "A, AIS, signalbehandling"
 #           file: projects-migrated/prosjekter-m2-jupyter/a-ais/index.qmd
          - text: "A, Elektro, telegrafister"
            file: projects-migrated/prosjekter-m2-jupyter/a-elektro/index.qmd
          - text: "B, Varme"
            file: projects-migrated/prosjekter-m2-jupyter/b-1/index.qmd
          - text: "B, Bølger"
            file: projects-migrated/prosjekter-m2-jupyter/b2-forny-skip-hav/index.qmd
          - text: "C, Fluider"
            file: projects-migrated/prosjekter-m2-jupyter/c-bygg/index.qmd
          - text: "D, Data, Bildebehandling"
            file: projects-migrated/prosjekter-m2-jupyter/d-data/index.qmd
          - text: "D, Logistikk, Trafikk"
            file: projects-migrated/prosjekter-m2-jupyter/d-logistikk/index.qmd  
          - text: "Varmetransport 25"
            file: projects-migrated/prosjekt-ny/ prosjektoppgave-imax2022-imax2023-imax2024/index.qmd 
            
      - section: "Matematikk 2 - programmoduler"
        contents:
          - text: "A, Elektro, telegrafister"
            file: projects-migrated/prosjekter-m2-jupyter/a-elektro-del2/index.qmd
          - text: "B, Varme"
            file: projects-migrated/prosjekter-m2-jupyter/b-1-del2/index.qmd
          - text: "B, Bølger"
            file: projects-migrated/prosjekter-m2-jupyter/b2-forny-skip-hav-del2/index.qmd
          - text: "C, Fluider"
            file: projects-migrated/prosjekter-m2-jupyter/c-bygg-del2/index.qmd
          - text: "D, Data, Bildebehandling"
            file: projects-migrated/prosjekter-m2-jupyter/d-data-del2/index.qmd
          - text: "D, Logistikk, Trafikk"
            file: projects-migrated/prosjekter-m2-jupyter/d-logistikk-del2/index.qmd
            
      - section: "Nye prosjekter"
        contents:
          - text: "Biohydrogen"
            file: projects-migrated/prosjekter-m1-runde-2/biohydrogen-pilot-student/index.qmd
          - text: "Blysyrebatteri"
            file: projects-migrated/prosjekter-m1-runde-2/blysyrebatteri-pilot-student/index.qmd
          - text: "Cellelogistikk"
            file: projects-migrated/prosjekter-m1-runde-2/cellelogistikk-pilot-student/index.qmd
          - text: "DC motor"
            file: projects-migrated/prosjekter-m1-runde-2/dc-motor-pilot-student/index.qmd
          - text: "Flystabilitet"
            file: projects-migrated/prosjekter-m1-runde-2/flystabilitet-turbulens-pilot-student/index.qmd
          - text: "Fuktig kjeller"
            file: projects-migrated/prosjekter-m1-runde-2/fuktig-kjeller-pilot-student/index.qmd
          - text: "Gjøvik space agency"
            file: projects-migrated/prosjekter-m1-runde-2/gjovik-space-agency-pilot-student/index.qmd
          - text: "Glidelager"
            file: projects-migrated/prosjekter-m1-runde-2/glidelager-pilot-student-v2/index.qmd
          - text: "Kavitasjon"
            file: projects-migrated/prosjekter-m1-runde-2/kavitasjon-pilot-student/index.qmd
          - text: "Kjernedannelse"
            file: projects-migrated/prosjekter-m1-runde-2/kjernedannelse-pilot-student-v2/index.qmd
          - text: "Lakselogistikk"
            file: projects-migrated/prosjekter-m1-runde-2/lakselogistikk-pilot-student/index.qmd
          - text: "Plastisk deformasjon"
            file: projects-migrated/prosjekter-m1-runde-2/plastisk-deformasjon-pilot-student/index.qmd
          - text: "Pumpekraftverk"
            file: projects-migrated/prosjekter-m1-runde-2/pumpekraftverk-pilot-student/index.qmd
          - text: "Robot kinematikk"
            file: projects-migrated/prosjekter-m1-runde-2/robotkinematikk-pilot-student/index.qmd
          - text: "Rust"
            file: projects-migrated/prosjekter-m1-runde-2/rust-oksygentransport-pilot-student/index.qmd
          - text: "Saltkraft"
            file: projects-migrated/prosjekter-m1-runde-2/saltkraftverk-pilot-student/index.qmd
          - text: "Skipstabilitet"
            file: projects-migrated/prosjekter-m1-runde-2/skipstabilitet-turbulens-pilot-student/index.qmd
          - text: "Solcelle"
            file: projects-migrated/prosjekter-m1-runde-2/solcelle-dc-buss-pilot-student/index.qmd
          - text: "Transformator"
            file: projects-migrated/prosjekter-m1-runde-2/transformator-pilot-student/index.qmd
          - text: "Vannett"
            file: projects-migrated/prosjekter-m1-runde-2/vannett-trykk-scc-pilot-student/index.qmd
          - text: "Varmestråling i bygg"
            file: projects-migrated/prosjekter-m1-runde-2/varmestraling-bygg-radiositet-pilot-student/index.qmd
          - text: "Watt kobling"
            file: projects-migrated/prosjekter-m1-runde-2/watt-kobling-pilot-student/index.qmd
                                    
           


format:
  html:
    theme: cosmo
    css: styles.css
